version: '3.8'
services:
  app:
    container_name: agisserver
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://agisagent:Agis%402024@mongodb:27017/
    ports:
      - '3001:3001'
    depends_on:
      - database
    networks:
      - dbnetwork

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: agisagent
      MONGO_INITDB_ROOT_PASSWORD: Agis@2024
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge
